DROP TABLE ORSZAG;
DROP TABLE KONTINENS;
CREATE TABLE CSILLAG
(
    CSILLAG_ID                  INTEGER  PRIMARY KEY   NOT NULL,
    ELNEVEVEZESEK               VARCHAR2(250)               NOT NULL,
    TAVOLSAG_A_NAPTOL_NEZVE     NUMBER  CHECK(TAVOLSAG_A_NAPTOL_NEZVE>0),
    SPEKTALIS_OSZTALY           VARCHAR2(2),
    EVOLUCIOS_FAZIS             VARCHAR2(4),
    TOMEG                       NUMBER CHECK(TOMEG>0),
    LAKHATOSAGI_ZONA            VARCHAR2(10),
    EGYEB_FONTOS_INFORMACIO     VARCHAR2(250)
);

CREATE TABLE BOLYGO
(
    BOLYGO_ID                  INTEGER PRIMARY KEY                 NOT NULL,
    ELNEVEVEZESEK               VARCHAR2(250)                       NOT NULL,
    TOMEG                       NUMBER CHECK(TOMEG>0),
    FELFEDEZES_DATUMA           DATE                                NOT NULL,
    GRAVITACIO                  NUMBER,
    HOLDAK_SZAMA                INTEGER CHECK(HOLDAK_SZAMA >0),
     VAN_E_GYURUJE              VARCHAR2(5) ,
    EGYEB_FONTOS_INFORMACIO     VARCHAR2(250),
    CONSTRAINT GYURU_JO         CHECK(VAN_E_GYURUJE = 'van' OR VAN_E_GYURUJE = 'nincs')
);
CREATE TABLE KORULOTTE_KERING
(
    PERIASZTON_TAVOLSAG NUMBER,
    APASZTRON_TAVOLSAG NUMBER,
    KERINGESI_IDO       NUMBER NOT NULL,
    CSILLAG_ID          INTEGER   NOT NULL,
    BOLYGO_ID           INTEGER   NOT NULL,
    CONSTRAINT CSILLAG_ID_FK
            FOREIGN KEY (CSILLAG_ID)
            REFERENCES CSILLAG(CSILLAG_ID),
    CONSTRAINT BOLYGO_ID_FK
            FOREIGN KEY (BOLYGO_ID)
            REFERENCES BOLYGO(BOLYGO_ID)
);